# Generated by Django 5.2.7 on 2025-12-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='zipcode',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
