# Generated by Django 5.2.7 on 2026-02-18 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_alter_cartitem_unique_together_cart_cartitem_cart_and_more"),
        ("coupon", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="coupon.coupon",
            ),
        ),
    ]
